-- V1: baseline schema for the Patient Management System (solo doctor, single machine)
-- All schema changes MUST go through Flyway migrations (constitution Principle IV).

CREATE TABLE doctor_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE doctor_clinic_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_name VARCHAR(200) NOT NULL,
    clinic_name VARCHAR(200) NOT NULL,
    contact_details VARCHAR(500) NOT NULL,
    registration_number VARCHAR(100) NOT NULL
);

CREATE TABLE backup_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_backup_at TIMESTAMP NULL
);

-- Singleton row for backup_metadata so the app always has exactly one row to read/update.
INSERT INTO backup_metadata (id, last_backup_at) VALUES (1, NULL);

CREATE TABLE patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(200) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(50) NOT NULL,
    address VARCHAR(500) NULL,
    emergency_contact VARCHAR(200) NULL,
    phone_number VARCHAR(50) NOT NULL,
    email VARCHAR(200) NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Indexes to keep search fast at scale (SC-001).
CREATE INDEX idx_patient_full_name ON patient (full_name);
CREATE INDEX idx_patient_phone_number ON patient (phone_number);
CREATE INDEX idx_patient_is_deleted ON patient (is_deleted);

CREATE TABLE medical_history_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    entry_date DATE NOT NULL,
    diagnosis CLOB NOT NULL,
    prescription CLOB NULL,
    notes CLOB NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_history_patient FOREIGN KEY (patient_id) REFERENCES patient (id)
);

CREATE INDEX idx_history_patient_id ON medical_history_entry (patient_id);
CREATE INDEX idx_history_entry_date ON medical_history_entry (entry_date);
CREATE INDEX idx_history_is_deleted ON medical_history_entry (is_deleted);
