-- V3: prescriptions and clinical notes now live on medical_history_entry.
ALTER TABLE medical_history_entry ADD COLUMN IF NOT EXISTS prescription CLOB NULL;
ALTER TABLE medical_history_entry ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE medical_history_entry ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
ALTER TABLE medical_history_entry ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS prescription (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  prescribed_date DATE NOT NULL,
  details CLOB NOT NULL,
  is_current BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS personal_note (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL UNIQUE,
  content CLOB NULL,
  updated_at TIMESTAMP NOT NULL
);

UPDATE medical_history_entry
SET updated_at = created_at
WHERE updated_at IS NULL;

INSERT INTO medical_history_entry (patient_id, entry_date, diagnosis, prescription, notes, is_deleted, deleted_at, created_at, updated_at)
SELECT p.patient_id, p.prescribed_date, 'Prescription', p.details, NULL, FALSE, NULL, p.created_at, p.created_at
FROM prescription p
WHERE NOT EXISTS (
    SELECT 1
    FROM medical_history_entry h
    WHERE h.patient_id = p.patient_id
      AND h.entry_date = p.prescribed_date
      AND h.prescription = p.details
);

UPDATE medical_history_entry h
SET notes = COALESCE(NULLIF(h.notes, ''), (
    SELECT n.content
    FROM personal_note n
    WHERE n.patient_id = h.patient_id
))
WHERE EXISTS (
    SELECT 1
    FROM personal_note n
    WHERE n.patient_id = h.patient_id
      AND n.content IS NOT NULL
      AND TRIM(n.content) <> ''
);

ALTER TABLE medical_history_entry ALTER COLUMN updated_at SET NOT NULL;

DROP TABLE IF EXISTS personal_note;
DROP TABLE IF EXISTS prescription;

CREATE INDEX IF NOT EXISTS idx_history_is_deleted ON medical_history_entry (is_deleted);